//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWMS.DataClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DayWordPad
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> BlotterDate { get; set; }
        public string BlotterSort { get; set; }
        public string Motif { get; set; }
        public string Wordpad { get; set; }
    }
}
