//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWMS.DataClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TrainNote
    {
        public string ID { get; set; }
        public string Stu_ID { get; set; }
        public string TrainFashion { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Speciality { get; set; }
        public string TrainUnit { get; set; }
        public string KulturMemo { get; set; }
        public Nullable<double> Charge { get; set; }
        public string Effect { get; set; }
    }
}
